# Maintainer: Alexander Hill <ahill@breadpudding.dev>
SRC_HASH="9d4c124d7d731a2db399f6278baa2b42c2e3511f610c6ad30cc3f1a52581334b"
SRC_NAME="toybox"
SRC_PATCHES="9286b275af8cd81a2063e84bee13c94b04f335c50cb62ec4b32683d2b03674f2  .config"
SRC_REVISION=1
SRC_URL="https://landley.net/toybox/downloads/toybox-0.8.13.tar.gz"
SRC_VERSION="0.8.13"

# TODO: Remove halt

build() {
    tar xzf ../$SRC_FILENAME
    cd toybox-$SRC_VERSION/
    # NOTE: Toybox is still using egrep instead of grep -E. This will fix that
    #       and prevent errors later on. ~ahill
    sed -i "s/egrep/grep -E/" scripts/make.sh
    # NOTE: Even though we aren't using the default configuration anymore, it
    #       will fail to build because it seems to rely on *other* components
    #       generated by this step. ~ahill
    make defconfig
    cp ../.config .
    make -j $TT_PROCS
    mkdir -p $TT_INSTALLDIR$TT_BINDIR
    PREFIX=$TT_INSTALLDIR$TT_BINDIR ./scripts/install.sh --symlink
}
