# Maintainer: Alexander Hill <ahill@breadpudding.dev>
SRC_HASH="aada4722db8bcfa0b9732851856d405082b6a4fa2e3ab067be8db17cdd115b38"
SRC_NAME="linux"
SRC_PATCHES="5be339ea41c58a4b23affcca98d4ba618b8b17ebc25f6931769bbdbfecd211e3  linux.skylake.config"
SRC_URL="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.19.8.tar.xz"
SRC_VERSION="6.19.8"

build() {
    tar xJf ../$SRC_FILENAME
    cd linux-$SRC_VERSION/
    # NOTE: LLVM=1 is required for ALL invocations of the kernel's Makefile. GNU
    #       tools are still used by default in a lot of places and this will
    #       override them with LLVM tools wherever possible. ~ahill
    LLVM=1 make mrproper
    # NOTE: YACC defaults to bison, which doesn't exist here, so we tell it
    #       where to find the parser generator manually. ~ahill
    #LLVM=1 make -j $TT_PROCS menuconfig YACC=byacc
    cp ../linux.$TT_MICROARCH.config .config
    # NOTE: Apparently, byacc doesn't emit a reference to yylval, which causes
    #       an error when clang attempts to compile code generated by flex. I
    #       wasn't able to find any issues reported for the Linux kernel
    #       specifically, but I found another project with a similar issue. By
    #       simply promising clang that the symbol *will* exist, it was able to
    #       link genksyms without another problem. ~ahill
    sed -i '/#include "parse.tab.h"/aextern YYSTYPE yylval;' scripts/genksyms/lex.l
    # NOTE: sbase's version of dd doesn't understand status=* so we simply
    #       remove it when building the kernel. The only noticable difference is
    #       that the output of dd is visible, even when the Makefile is set to
    #       quiet, which is the default. I think I'll live. ~ahill
    sed -i "s/ status=.*;/;/" arch/x86/boot/Makefile
    # NOTE: Why is -n even being passed here? bzImage is a file, plus sbase's ln
    #       doesn't support the switch. Patching that out as well. ~ahill
    sed -i "s/ln -fsn/ln -fs/" arch/x86/Makefile
    LLVM=1 make -j $TT_PROCS YACC=byacc
    make -j $TT_PROCS install INSTALL_PATH=$TT_INSTALLDIR/boot
    make -j $TT_PROCS modules_install INSTALL_MOD_PATH=$TT_INSTALLDIR
    # NOTE: We don't use the built-in headers_install target because it requires
    #       rsync for some reason. ~ahill
    LLVM=1 make -j $TT_PROCS headers ARCH=$TT_ARCH
    find usr/include -type f ! -name "*.h" -delete
    mkdir -p $TT_INSTALLDIR/usr/include
    cp -r usr/include/* $TT_INSTALLDIR/usr/include/
    # TODO: Run dtbs_install on non-x86 systems ~ahill
}
